export enum AudioBotSound {
	BEGIN = "BEGIN",
	GAME_OVER = "GAME_OVER",
	TAKE_POSITION = "TAKE_POSITION",
	OUT_OF_BOUNDS = "OUT_OF_BOUNDS",
	OVERTIME = "OVERTIME",
	TIMEOUT = "TIMEOUT",
	ANCHORS = "ANCHORS",
	FOUR_SHIPS = "4_SHIPS",
	THREE_SHIPS = "3_SHIPS",
	TWO_SHIPS = "2_SHIPS",
}
